muscle:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features: 
  - beSqlQueries
  - compiledGroovy
  - logging
  l10n: ru
  modules:
  - core:
      entities: []
  application:
  - _welcome_
  - organisms
  - series
  - individuals
  scripts:
  - common
  - dictionaries
  - users
  - Post-db
  - GSE120862
  includes:
  - common
