muscle:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features: 
  - beSqlQueries
  - compiledGroovy
  - logging
  l10n: ru
  modules:
  - core:
      entities: []
  application:
  - _welcome_
  - biosamples
  - cells
  - comparisons
  - conditions
  - individuals
  - organisms
  - platforms
  - samples
  - series
  - tissues
  - treatments
  scripts:
  - common
  - dictionaries
  - users
  - Post-db
  - GSE120862
  - GSE86931
  includes:
  - common
