muscle:
  projectFileStructure:
    groovyQueriesDir: src/main/groovy
    groovyOperationsDir: src/main/groovy
    groovyExtendersDir: src/main/groovy
  features: 
  - beSqlQueries
  - compiledGroovy
  - logging
  l10n: ru
  modules:
  - core:
      entities: []
  application:
  - _genes_
  - _welcome_
  - biosamples
  - cells
  - comparisons
  - conditions
  - individuals
  - gene2counts_human
  - genes_human
  - measurements_tmp  
  - measurements_1  
  - measurements_1_targets  
  - organisms
  - platforms
  - samples
  - series
  - tissues
  - treatments
  scripts:
  - common
  - dictionaries
  - users
  - Post-db
  - GSE_all
  - GSE120862
  - GSE86931
  - GSE107934
  - GSE60591
  - GSE123878
  - GSE63887
  - GSE58387
  - GSE87748
  - GSE141827
  - GSE99963
  - GSE134698
  - GSE71972
  - GSE108643
  - GSE97084
  - measurements_tmp  
  - measurements_1  
  includes:
  - common
